### ISSUE TITLE
Completely confused

### ISSUE THREAD

**Issue by Gelox1209** [DRE2N/CommandsXL#2]
commands:
  version: [world]
  help: []
  deop %name%: []
permission: 'my.awesome.permission.node'

So in the above example, I'm trying to make sense of all of this, so in the brackets I can only put in worlds to restrict where you can use the commands and the permission node is for all the commands that is enlisted under "commands:"? And the commands has to be already in the server in order for me to throw it in the configs? 

For example: 

mi Wand Magicwand1:[]
Cannot be
givewand:[mi Wand Magicwand1]

? I'm so confused right now.

*Side note: I'm using this in order for me to use it along with the dungeonsxl plugin.*

**Comment by Sataniel98** [comment]
Don't really get what you don't understand. CommandsXL basically links all these commands together to one. The permission node grants access to the linked command and the world lists are irrelevant for DungeonsXL. You could use them to exclude some of the commands from being executed when the linked command is performed in a world that isn't whitelisted. I have no idea what your example is supposed to show.

**Comment by Gelox1209** [comment]
So in the example you provided:
commands:
version: [world]
help: []
deop %name%: []
permission: 'my.awesome.permission.node'

It means that when you do /commands it does all the command listed below?

**Comment by Sataniel98** [comment]
The command to enter would be "/commandsxl,cxl [console|op|default] [file name of the linked command without .yml] [delay in seconds]" and not "/commands", but yes. Except the command "/version" if the command sender is not in the world "world". As you might have noticed, these are exactly the arguments you'd pass to the command sign in DXL as well (console/op/default, linked command script name, delay...)

**Comment by Gelox1209** [comment]
Ok ok I got it, thanks~!
